version: "3.8"

services:
  api:
    image: atendai/evolution-api:latest
    restart: always
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    expose:
      - "8080"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://127.0.0.1:8080/ || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  evolution_instances: