version: "3.8"

services:
  api:
    image: evoapicloud/evolution-api:latest  # official image
    restart: always
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    expose:
      - "8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.evoapi.rule=Host(`evo1api.ezcrm.top`)
      - traefik.http.routers.evoapi.entrypoints=web,websecure
      - traefik.http.routers.evoapi.tls=true
      - traefik.http.services.evoapi.loadbalancer.server.port=8080
      - traefik.docker.network=coolify
    networks:
      - coolify

networks:
  coolify:
    external: true
    name: coolify

volumes:
  evolution_instances: